language: node_js

node_js:
  - '9.11.2'

dist: trusty

services:
  - mongodb
  - redis-server

env:
  - NODE_ENV=ci PORT=3000

cache:
  directories:
    - node_modules
    - client/node_modules

install:
  - npm i -g npm@6.5.0
  - npm install --silent
  - npm run build

script:
  - nohup npm run start &
  - sleep 3
  - npm run test

